apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: koo-swimming-
  namespace: argo
spec:
  entrypoint: koo-swimming
  arguments:
    parameters:
      - name: revision
        value: master
      - name: repo
        value: https://github.com/binayakd/koo-swimming.git
  templates:
  - name: koo-swimming
    inputs:
      artifacts:
        - name: repo
          path: /repo
          git:
            repo: "{{workflow.parameters.repo}}"
            revision: "{{workflow.parameters.revision}}"
    container:
      image: docker:git
      command: [sh, -c]
      args: ["until docker ps; do sleep 3; done; cd /repo; ls-al; docker run --rm debian:latest cat /etc/os-release"]
      env:
          - name: DOCKER_HOST               # the docker daemon can be access on the standard port on localhost
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:dind          # Docker already provides an image for running a Docker daemon
          securityContext:
            privileged: true                # the Docker daemon can only run in a privileged container
          # mirrorVolumeMounts will mount the same volumes specified in the main container
          # to the sidecar (including artifacts), at the same mountPaths. This enables
          # dind daemon to (partially) see the same filesystem as the main container in
          # order to use features such as docker volume binding.
          mirrorVolumeMounts: true