spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

---

spring:
  profiles: default

filepath: "target/file/"

---

spring:
  profiles: dev

filepath: "/usr/src/app/"
